repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 #v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.260
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 23.1.0 #22.3.0
    hooks:
    -   id: black
        exclude: ^.github/
